stages:
  - test

.test_job: &test_job
  stage: test
  
  script:
    - wmllint --dryrun /usr/share/games/wesnoth/$VERSION/data/core .

test:default:
  <<: *test_job
  image: konecnyjakub/wesnoth:1.16
  variables:
    VERSION: "1.16"
