stages:
  - test

.test_job: &test_job
  stage: test
  
  script:
    - /usr/share/games/wesnoth/data/tools/wmllint --dryrun /usr/share/games/wesnoth/data/core .

test:default:
  <<: *test_job
  image: konecnyjakub/wesnoth:1.18
  variables:
    VERSION: "1.18"
